data:
  root_folder: /Users/Edu/data/ucl-neuropixel
  recordings: neuropixel.bin
  geometry: channel_positions.npy

resources:
  max_memory: 1000000000

recordings:
  dtype: int16
  sampling_rate: 30000
  n_channels: 374
  spatial_radius: 70
  spike_size_ms: 1.5
  format: wide

preprocess:
  filter: True
  dtype: float32

detect:
  method: threshold
  temporal_features: 3

deconvolution:
  rank: 3
  threshold: 4
  lam: 20

neural_network_detector:
  filename: detect_nn1.ckpt
  threshold_spike: 0.5

neural_network_triage:
  filename: triage_nn1.ckpt
  threshold_collision: 0.9

neural_network_autoencoder:
  filename: ae_nn1.ckpt
