#!/usr/bin/env bash

# Run yass uni tests with a special flag, some tests will save their output
# so we can use it as reference
export YASS_SAVE_OUTPUT_REFERENCE=1
pytest tests/unit/
unset YASS_SAVE_OUTPUT_REFERENCE

# copy generated test data to the original place so all gets uploaded
cp -r tests/assets/output_reference/ "$1/yass-testing-data/output_reference"